SageERP/Controllers/AuditFeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using Shampan.Core.Interfaces.Repository.AuditFeedbackRepo;
using Shampan.Core.Interfaces.Services.AuditFeedbackService;
using Shampan.Core.Interfaces.Services.AuditIssues;
using Shampan.Models;
using Shampan.Models.AuditModule;
using Shampan.Services.AuditIssues;
using ShampanERP.Models;
using ShampanERP.Persistence;
using StackExchange.Exceptional;

namespace SSLAudit.Controllers
{
	[ServiceFilter(typeof(UserMenuActionFilter))]

	public class AuditFeedbackController : Controller
    {

        private readonly ApplicationDbContext _applicationDb;
        private readonly IAuditFeedbackService _auditFeedbackService;
        private readonly IAuditFeedbackAttachmentsService _auditFeedbackAttachmentsService;

        public AuditFeedbackController(ApplicationDbContext applicationDb, IAuditFeedbackService auditFeedbackService,
            IAuditFeedbackAttachmentsService auditFeedbackAttachmentsService)
        {
            _applicationDb = applicationDb;
            _auditFeedbackService = auditFeedbackService;
            _auditFeedbackAttachmentsService = auditFeedbackAttachmentsService;
        }



        public IActionResult Index(int? id)
        {
            if (id is null || id == 0)
            {
                return RedirectToAction("Index", "Audit");
            }

            AuditFeedback auditIssue = new AuditFeedback()
            {
                AuditId = id.Value
            };

            return View(auditIssue);
        }

        public IActionResult Create(int? id)
        {

            if (id is null || id == 0)
            {
                return RedirectToAction("Index", "Audit");
            }

            AuditFeedback auditIssue = new AuditFeedback()
            {
                Operation = "add",
                AuditId = id.Value
            };
            return View(auditIssue);
        }


        [HttpPost]
        public ActionResult CreateEdit(AuditFeedback master)
        {
            ResultModel<AuditFeedback> result = new ResultModel<AuditFeedback>();
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);

                if (master.Operation == "update")
                {

                    master.Audit.LastUpdateBy = user.UserName;
                    master.Audit.LastUpdateOn = DateTime.Now;
                    master.Audit.LastUpdateFrom = "";

                    result = _auditFeedbackService.Update(master);

                    //if (result.Status == Status.Fail)
                    //{
                    //    throw result.Exception;
                    //}


                    return Ok(result);
                }


                master.Audit.CreatedBy = user.UserName;
                master.Audit.CreatedOn = DateTime.Now;
                master.Audit.CreatedFrom = "";
                master.Audit.LastUpdateBy = user.UserName;
                master.Audit.LastUpdateOn = DateTime.Now;
                master.Audit.LastUpdateFrom = "";



                result = _auditFeedbackService.Insert(master);

                //if (result.Status == Status.Fail)
                //{
                //    throw result.Exception;
                //}


                return Ok(result);


            }
            catch (Exception ex)
            {
                ex.LogAsync(ControllerContext.HttpContext);
            }

            return Ok(result);
        }

        public ActionResult<IList<AuditFeedback>> Edit(int id)
        {
            try
            {
                ResultModel<List<AuditFeedback?>> result =
                    _auditFeedbackService.GetAll(new[] { "Id" }, new[] { id.ToString() });

                if (result.Status == Status.Fail)
                {
                    throw result.Exception;
                }

                AuditFeedback? auditMaster = result.Data.FirstOrDefault();

                auditMaster.AttachmentsList = _auditFeedbackAttachmentsService
                    .GetAll(new[] {"AuditFeedbackId"}, new[] {id.ToString()}).Data;

                auditMaster.Operation = "update";

                return View("Create", auditMaster);
            }
            catch (Exception e)
            {
                e.LogAsync(ControllerContext.HttpContext);
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        public ActionResult<IList<AuditFeedback>> _index(int? id)
        {
            try
            {
                //if (id is null || id == 0)
                //{
                //    return Ok(new { Data = new List<AuditFeedback>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
                //}


                IndexModel index = new IndexModel();
                string userName = User.Identity.Name;
                ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);



                string? search = Request.Form["search[value]"].FirstOrDefault();



                string draw = Request.Form["draw"].ToString();
                var startRec = Request.Form["start"].FirstOrDefault();
                var pageSize = Request.Form["length"].FirstOrDefault();
                var orderName = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][Name]"].FirstOrDefault();

                var orderDir = Request.Form["order[0][dir]"].FirstOrDefault();

                index.SearchValue = Request.Form["search[value]"].FirstOrDefault();
				//index.OrderName = orderName;
				//index.orderDir = orderDir;
				index.OrderName = "Id";
				index.orderDir = "desc";
				index.startRec = Convert.ToInt32(startRec);
                index.pageSize = Convert.ToInt32(pageSize);

                index.createdBy = userName;
                index.AuditId = id.Value;



                string[] conditionalFields = new[]
                {
                    "ai.IssueName like",
                    "af.Heading like"
                };
                string?[] conditionalValue = new[] { search, search };


                ResultModel<List<AuditFeedback>> indexData =
                    _auditFeedbackService.GetIndexData(index,
                conditionalFields, conditionalValue);


                ResultModel<int> indexDataCount =
                    _auditFeedbackService.GetIndexDataCount(index,
                conditionalFields, conditionalValue);

                int result = _auditFeedbackService.GetCount(TableName.A_Audits, "Id", null,null);

                // data, draw, recordsTotal = TotalReocrd, recordsFiltered = data.Count
                return Ok(new { data = indexData.Data, draw, recordsTotal = result, recordsFiltered = indexDataCount.Data });
            }
            catch (Exception e)
            {
                e.LogAsync(ControllerContext.HttpContext);
                return Ok(new { Data = new List<AuditIssue>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
            }
        }

        [HttpPost]
        public ActionResult<IList<AuditFeedback>> _indexBranchFeedback(int? id)
        {
            try
            {
                //if (id is null || id == 0)
                //{
                //    return Ok(new { Data = new List<AuditFeedback>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
                //}


                IndexModel index = new IndexModel();
                string userName = User.Identity.Name;
                ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);



                string? search = Request.Form["search[value]"].FirstOrDefault();



                string draw = Request.Form["draw"].ToString();
                var startRec = Request.Form["start"].FirstOrDefault();
                var pageSize = Request.Form["length"].FirstOrDefault();
                var orderName = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][Name]"].FirstOrDefault();

                var orderDir = Request.Form["order[0][dir]"].FirstOrDefault();

                index.SearchValue = Request.Form["search[value]"].FirstOrDefault();
				index.OrderName = orderName;
				index.orderDir = orderDir;
				//index.OrderName = "Id";
				//index.orderDir = "desc";
				index.startRec = Convert.ToInt32(startRec);
                index.pageSize = Convert.ToInt32(pageSize);

                index.createdBy = userName;
                index.AuditId = id.Value;



                string[] conditionalFields = new[]
                {
                    "ai.IssueName like",
                    "ad.Name like"
                };
                string?[] conditionalValue = new[] { search, search };


                ResultModel<List<AuditFeedback>> indexData =
                    _auditFeedbackService.GetIndexData(index,
                conditionalFields, conditionalValue);


                ResultModel<int> indexDataCount =
                    _auditFeedbackService.GetIndexDataCount(index,
                conditionalFields, conditionalValue);

                int result = _auditFeedbackService.GetCount(TableName.A_Audits, "Id", null, null);

                // data, draw, recordsTotal = TotalReocrd, recordsFiltered = data.Count
                return Ok(new { data = indexData.Data, draw, recordsTotal = result, recordsFiltered = indexDataCount.Data });
            }
            catch (Exception e)
            {
                e.LogAsync(ControllerContext.HttpContext);
                return Ok(new { Data = new List<AuditIssue>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
            }
        }

     

        [HttpPost]
        public IActionResult DeleteFile(string filePath, string id)
        {
            string saveDirectory = "wwwroot\\files";

SageERP/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shampan.Core.Interfaces.Services.Company;
using Shampan.Core.Interfaces.Services.UserRoll;
using Shampan.Models;
using Shampan.Models.AuditModule;
using ShampanERP.Models;
using ShampanERP.Persistence;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using System.Security.Policy;
using Microsoft.AspNetCore.Hosting.Server.Features;
using SSLAudit.Controllers;
using SSLAudit.Models;
using Microsoft.Extensions.Caching.Memory;

namespace ShampanERP.Controllers
{
    [ServiceFilter(typeof(UserMenuActionFilter))]

    public class LoginController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;
        private readonly ApplicationDbContext _context;
        private readonly ICompanyInfoService _companyInfoService;
		private readonly IMemoryCache _memoryCache;

		private DbConfig _dbConfig;

        public LoginController(
           UserManager<ApplicationUser> userManager,
           SignInManager<ApplicationUser> signInManager,
           RoleManager<IdentityRole> roleManager,
           IConfiguration configuration,
           ApplicationDbContext context,

			IMemoryCache memoryCache



			, ICompanyInfoService companyInfoService, DbConfig dbConfig)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _configuration = configuration;
            _context = context;
            _companyInfoService = companyInfoService;
			_memoryCache = memoryCache;


			this._dbConfig = dbConfig;

		}


        public IActionResult Index(string returnurl)
        {


            List<CompanyInfo> companyInfos = new List<CompanyInfo>();
            LoginResource loginModel = new LoginResource();

			var resultModel = _companyInfoService.GetAll(null, null);

			if (resultModel.Status == Status.Success)
			{
				companyInfos = resultModel.Data;
			}

            loginModel.CompanyInfos = companyInfos;
            loginModel.returnUrl = returnurl;




            return View(loginModel);
        }

		public async Task<IActionResult> CreateClaims()
		{
			string SageDbName = _dbConfig.SageDbName;

			string userName = "erp";

			var user = _userManager.Users.SingleOrDefault(x => x.UserName == userName);

			IdentityResult? result = await _userManager.AddClaimAsync(user, new Claim(ClaimNames.SageDatabase, SageDbName));



			return RedirectToAction("Index", "Home");

		}



        [HttpPost]
        public async Task<ActionResult> Index(LoginResource model, string returnurl)
        {


            //Uri returnurl = new Uri(Request.Host.ToString());
            var location = new Uri($"{Request.Scheme}://{Request.Host}{Request.Path}{Request.QueryString}");

            var url = location.AbsoluteUri;
            List<CompanyInfo> companyInfos = new List<CompanyInfo>();
            var resultModel = _companyInfoService.GetAll(null, null);
            if (resultModel.Status == Status.Success)
            {
                companyInfos = resultModel.Data;
            }
            model.CompanyInfos = companyInfos;


            //if (!ModelState.IsValid)
            //{
            //    //ModelState.AddModelError("UserName", "Invalid Username ");


            //    return View(model);

            //}


            var result = await _signInManager.PasswordSignInAsync(model.UserName, model.Password, false, false);


            if (!result.Succeeded)
            {
                ModelState.AddModelError("Message", "Wrong username or password");

                return View(model);
            }

            var user = _userManager.Users.SingleOrDefault(x => x.UserName == model.UserName);

            if (user == null)
            {
                ModelState.AddModelError("Message", "Wrong username or password");

                return View(model);
            }


            IList<string> roles = await _userManager.GetRolesAsync(user);

            var userClaims = await _userManager.GetClaimsAsync(user);

            var dbClaim = userClaims.FirstOrDefault(x => x.Type == ClaimNames.Database);

            if (dbClaim == null)
            {
                ModelState.AddModelError("Message", "Wrong username or password");

                return View(model);
            }

            if (dbClaim.Value != model.CompanyName)
            {
                ModelState.AddModelError("Message", "Wrong username or password");

                return View(model);
            }


            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.UserData, user.Id),
            };

            if (roles.Any())
                claims.AddRange(roles.Select(role => new Claim(ClaimTypes.Role, role)));

            claims.AddRange(userClaims);

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {

                IssuedUtc = DateTimeOffset.Now,

            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            ViewData["Username"] = model.UserName;
            //return RedirectToAction("Index", "Home");

            bool b = User.Identity.IsAuthenticated;
            string name = User.Identity.Name;
			//string[] parts = new string[] {"","" };

			//if (returnurl != null)
			//{
			//    //parts  = returnurl.TrimStart('/').Split('/');
			//     parts = returnurl.TrimStart('/').Split('/', '?');
			//}

			//parts  = returnurl.TrimStart('/').Split('/');
			//string a1 = parts[0]; // "Audit"
			//string b1 = parts[1]; // "Edit"
			//string c1 = parts[2]; // "155"


			//string query = parts[3]; 



			if (returnurl == null)
            {
                return RedirectToAction("Index", "Home");
                //return RedirectToAction("ApproveStatusIndex", "Audit");
            }
   //         {
            else //if(returnurl != null)
            {

				// return RedirectToAction(b1, a1);
				return Redirect(returnurl);

				// / Audit / ApproveStatusIndex
			
			}
            //else
            //{
            //    returnurl = "https://localhost:7031/Audit/Edit/234?edit=auditStatus";
            //    return Redirect(returnurl);
            //}

			//}

        }
    }
		}
            

SageERP/Views/AuditFeedback/Create.cshtml
@using Shampan.Models
@using Shampan.Models.AuditModule
@model Shampan.Models.AuditModule.AuditFeedback
@{
    ViewData["Title"] = "Create";
}
@if (User.Identity.IsAuthenticated)
{
    var UserId = @User.Identity.Name;
}
else
{
    <script>window.location.href = '@Url.Action("Index", "Login")';</script>
}


@Html.Partial("_Header",new HeaderModel(){ HeaderName = "Audit Feedback Create", BreadCrums = new Dictionary<string, string>()
{
    {$"/AuditFeedback/index/{@Model.AuditId}","Audit Feedback"},
    {"","Create"},
}})


<div class="container-fluid">

    @using (Html.BeginForm("CreateEdit", "AuditFeedback", FormMethod.Post, new { @Id = "frm_Audit" }))
    {
        <!-- Master Start-->
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">Audit Feedback </h3>
            </div>
            <div class="card-body">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.AuditId)

                @Html.HiddenFor(model => model.Operation)

                <div class="form-group row">

                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.AuditIssueId)
                        @*@Html.TextBoxFor(model => model.AuditIssueId, new { @class = "  form-control input-sm" })*@
                        @Html.DropDownListFor(model => model.AuditIssueId, Enumerable.Empty<SelectListItem>(), new {@class = "form-control", @data_selected = Model.AuditIssueId})
                        @Html.ValidationMessageFor(model => model.AuditIssueId)
                    </div>



                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.Heading)
                        @Html.TextAreaFor(model => model.Heading, new { @class = "  form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.Heading)
                    </div>

                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.FeedbackDetails)
                        @Html.TextAreaFor(model => model.FeedbackDetails, new { @class = "  form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.FeedbackDetails)
                    </div>


                </div>


                <div class="row form-group">
                    <div class="col-md-3">
                        <div class="editor-label">
                            <label>Attachments</label>
                        </div>
                        <input type="file" accept=".jpg,.jpeg, .png,.pdf, .xls, .xlsx,.docx" id="fileToUpload" name="Attachments" multiple="multiple" />

                    </div>

                </div>

                <div class="row">
                    <ul class="list-group fileGroup">

                        @foreach (AuditFeedbackAttachments item in Model.AttachmentsList)
                        {
                            <li class="list-group-item" id="file-@item.Id">
                                <span>
                                    @item.DisplayName
                                </span>
                                <a target="_blank" href="/AuditIssue/DownloadFile?filePath=@item.FileName" class=" ml-2 btn btn-primary btn-sm float-right ml-2">Download</a>

                                <button onclick="AuditFeedbackController.deleteFile('@item.Id' ,'@item.FileName')" class=" ml-2 btn btn-danger btn-sm float-right" type="button">Delete</button>


                            </li>
                        }

                    </ul>
                </div>

            </div>
        </div>

        <!-- Master End-->
    }


</div>




<div class="container-fluid">
    <div class="card">
        <div class="card-header p-2">
            @if (Model.Operation.Equals("update", StringComparison.OrdinalIgnoreCase))
            {
                <button type="button" class="btn btn-primary  pt-1 btnSave">Update</button>
            }
            else
            {
                <button type="button" class="btn btn-primary  pt-1 btnSave">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            }
        </div>
    </div>
</div>


@section scripts{
    <script src="/js/app/Services/AuditFeedback/AuditFeedbackService.js"></script>
    <script src="/js/app/Controllers/AuditFeedback/AuditFeedbackController.js"></script>

    <script>

        $(document).ready(function () {
            AuditFeedbackController.init();
        });

    </script>


}

SageERP/Views/AuditFeedback/Index.cshtml
@model Shampan.Models.AuditModule.AuditFeedback



@{
    ViewData["Title"] = "Index";
}

@Html.Partial("_Header",new HeaderModel(){ HeaderName = "Audit Feedback", BreadCrums = new Dictionary<string, string>()
{
    {"/AuditFeedback/index/"+@Model.AuditId,"Audit Feedback"},
    {"","Index"},
}})

<div class="container-fluid">
    <div class="card">
        <div class="card-header p-2">
            <button type="button" title="Add New Audit"
                    data-url="/AuditFeedback/Create/@Model.AuditId" onclick="GoTo(this)"
                    id="" class="NewButton">
                <i class="fa fa-plus" aria-hidden="true"></i>
                &nbsp;
                New
            </button>

        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">
                List Of Data
            </h3>

        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped" id="AuditFeedList">
                <thead>
                <tr>
                    <th>Action</th>
                    <th>Audit Name</th>
                    <th>Issue Name</th>
                    <th>Issue Heading</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

</div>


@section scripts{

    <script src="/js/app/Services/AuditFeedback/AuditFeedbackService.js"></script>
    <script src="/js/app/Controllers/AuditFeedback/AuditFeedbackController.js"></script>

    <script>

        $(document).ready(function () {
            AuditFeedbackController.init({ auditId: @Model.AuditId});

        });

    </script>
}