SageERP/Controllers/Audit/AuditIssueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using SageERP.ExtensionMethods;
using Shampan.Core.Interfaces.Services.Audit;
using Shampan.Core.Interfaces.Services.AuditIssues;
using Shampan.Models;
using Shampan.Models.AuditModule;
using Shampan.Services.Audit;
using ShampanERP.Models;
using ShampanERP.Persistence;
using StackExchange.Exceptional;

namespace SSLAudit.Controllers.Audit
{
	[ServiceFilter(typeof(UserMenuActionFilter))]

	public class AuditIssueController : Controller
    {
        private readonly ApplicationDbContext _applicationDb;
        private readonly IAuditIssueService _auditIssueService;
        private readonly IAuditMasterService _auditMasterService;
        private readonly IAuditIssueAttachmentsService _auditIssueAttachmentsService;
		private readonly IAuditIssueUserService _auditIssueUserService;


		public AuditIssueController(ApplicationDbContext applicationDb, IAuditIssueUserService auditIssueUserService, IAuditIssueService auditIssueService, IAuditIssueAttachmentsService auditIssueAttachmentsService, IAuditMasterService auditMasterService)
        {
            _applicationDb = applicationDb;
            _auditIssueService = auditIssueService;
            _auditIssueAttachmentsService = auditIssueAttachmentsService;
            _auditMasterService = auditMasterService;
			_auditIssueUserService = auditIssueUserService;
        }

        public IActionResult Index(int? id)
        {
            if (id is null || id == 0)
            {
                return RedirectToAction("Index", "Audit");
            }

            AuditIssue auditIssue = new AuditIssue()
            {
                AuditId = id.Value
            };

            var auditMaster = _auditMasterService.GetAll(new[] { "Id" }, new[] { id.Value.ToString() }).Data;

            if (auditMaster != null && auditMaster.Count > 0)
            {
                auditIssue.AuditMaster = auditMaster.FirstOrDefault();
            }

            return View(auditIssue);
        }



        public IActionResult Create(int? id)
        {

            if (id is null || id == 0)
            {
                return RedirectToAction("Index", "Audit");
            }

            AuditIssue auditIssue = new AuditIssue()
            {
                Operation = "add",
                AuditId = id.Value
            };
            return View(auditIssue);
        }



        [HttpPost]
        public ActionResult CreateEdit(AuditIssue master)
        {
            ResultModel<AuditIssue> result = new ResultModel<AuditIssue>();
            try
            {
                string userName = User.Identity.Name;
                ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);

                if (master.Operation == "update")
                {

                    master.Audit.LastUpdateBy = user.UserName;
                    master.Audit.LastUpdateOn = DateTime.Now;
                    master.Audit.LastUpdateFrom = "";

                    result = _auditIssueService.Update(master);

                    //if (result.Status == Status.Fail)
                    //{
                    //    throw result.Exception;
                    //}


                    return Ok(result);
                }
                else
                {

                    master.Audit.CreatedBy = user.UserName;
                    master.Audit.CreatedOn = DateTime.Now;
                    master.Audit.CreatedFrom = "";
                    master.Audit.LastUpdateBy = user.UserName;
                    master.Audit.LastUpdateOn = DateTime.Now;
                    master.Audit.LastUpdateFrom = "";
                    result = _auditIssueService.Insert(master);

					//if (result.Status == Status.Fail)
					//{
					//    throw result.Exception;
					//}

					//save link of audit address

					//https://localhost:7031/Audit/Edit/28?edit=issue

					//Uri returnurl = new Uri(Request.Host.ToString());
					//string urlString = returnurl.ToString();
					//string Url = "https://" + urlString + "/Audit/Edit/" + result.Data.Id + "?edit=issueApprove";


					//MailSetting ms = new MailSetting();
					//ms.ApprovedUrl = Url;
					//ms.AuditIssueId = result.Data.Id;
					//_auditMasterService.SaveUrl(ms);


					//end




					return Ok(result);
                }

            }
            catch (Exception ex)
            {
                ex.LogAsync(ControllerContext.HttpContext);
            }

            return Ok(result);
        }

        [HttpPost]
        public ActionResult<IList<AuditIssue>> _index(int? id)
        {
            try
            {
                //if (id is null || id == 0)
                //{
                //    return  Ok(new { Data = new List<AuditIssue>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
                //}


                IndexModel index = new IndexModel();
                string userName = User.Identity.Name;
                ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);
                string? search = Request.Form["search[value]"].FirstOrDefault();




                string issuename = Request.Form["issuename"].ToString();
                string issuepriority = Request.Form["issuepriority"].ToString();
                string dateofsubmission = Request.Form["dateofsubmission"].ToString();




                string draw = Request.Form["draw"].ToString();
                var startRec = Request.Form["start"].FirstOrDefault();
                var pageSize = Request.Form["length"].FirstOrDefault();
                var orderName = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][Name]"].FirstOrDefault();

                var orderDir = Request.Form["order[0][dir]"].FirstOrDefault();

                index.SearchValue = Request.Form["search[value]"].FirstOrDefault();
				//index.OrderName = orderName;
				//index.orderDir = orderDir;
				index.OrderName = "Id";
				index.orderDir = "desc";
				index.startRec = Convert.ToInt32(startRec);
                index.pageSize = Convert.ToInt32(pageSize);

                index.createdBy = userName;
                index.AuditId = id.Value;



                string[] conditionalFields = new[]
                {
                    "IssueName like",
                    "Enums.EnumValue like",
                    "DateOfSubmission like"
                };
                string?[] conditionalValue = new[] { issuename, issuepriority, dateofsubmission };


                ResultModel<List<AuditIssue>> indexData =
                    _auditIssueService.GetIndexData(index,
                        conditionalFields, conditionalValue);


                ResultModel<int> indexDataCount =
                    _auditIssueService.GetIndexDataCount(index,
                        conditionalFields, conditionalValue);

                int result = _auditIssueService.GetCount(TableName.A_AuditIssues, "Id", new[]
                        {
                            "createdBy",
                        }, new[] { userName });

                // data, draw, recordsTotal = TotalReocrd, recordsFiltered = data.Count
                return Ok(new { data = indexData.Data, draw, recordsTotal = result, recordsFiltered = indexDataCount.Data });
            }
            catch (Exception e)
            {
                e.LogAsync(ControllerContext.HttpContext);
                return Ok(new { Data = new List<AuditIssue>(), draw = "", recordsTotal = 0, recordsFiltered = 0 });
            }
        }




        public ActionResult<IList<AuditIssue>> Edit(int id)
        {
            try
            {
                ResultModel<List<AuditIssue?>> result =
                    _auditIssueService.GetAll(new[] { "Id" }, new[] { id.ToString() });

                if (result.Status == Status.Fail)
                {
                    throw result.Exception;
                }

                AuditIssue? auditMaster = result.Data.FirstOrDefault();

                auditMaster.AttachmentsList  = _auditIssueAttachmentsService.GetAll(new[] {"AuditIssueId"}, new[] {id.ToString()}).Data;

                auditMaster.Operation = "update";

                return View("Create", auditMaster);
            }
            catch (Exception e)
            {
                e.LogAsync(ControllerContext.HttpContext);
                return RedirectToAction("Index");
            }
        }


		public ActionResult<IList<AuditIssueUser>> Delete(AuditIssueUser master)
		{
			try
			{

                ResultModel<AuditIssueUser> result = _auditIssueUserService.Delete(master.Id);
                //ResultModel<AuditMaster> result = new ResultModel<AuditMaster>();

				return Ok(result);

			}
			catch (Exception e)
			{
				e.LogAsync(ControllerContext.HttpContext);
				return RedirectToAction("Index");
			}
		}

		public ActionResult MultiplePost(AuditIssue master)
        {
            ResultModel<AuditIssue> result = new ResultModel<AuditIssue>();

            try
            {

                foreach (string ID in master.IDs)
                {


                    string userName = User.Identity.Name;
                    ApplicationUser? user = _applicationDb.Users.FirstOrDefault(model => model.UserName == userName);
                    master.Audit.PostedBy = user.UserName;
                    master.Audit.PostedOn = DateTime.Now;
                    master.Audit.PostedFrom = HttpContext.Connection.RemoteIpAddress.ToString();
                    master.Operation = "post";
                    result = _auditIssueService.MultiplePost(master);


                }




                return Ok(result);


            }
            catch (Exception ex)
            {
                ex.LogAsync(ControllerContext.HttpContext);
            }

            return Ok("");
        }

        public ActionResult MultipleUnPost(AuditIssue master)
        {

SageERP/Views/AuditIssue/Create.cshtml
@using Shampan.Models
@model Shampan.Models.AuditIssue
@{
    ViewData["Title"] = "Create";
}




@Html.Partial("_Header",new HeaderModel(){ HeaderName = "Audit Issue Create", BreadCrums = new Dictionary<string, string>()
{
    {$"/AuditIssue/index/{@Model.AuditId}","Audit Issue"},
    {"","Create"},
}})





<div class="container-fluid">

    @using (Html.BeginForm("CreateEdit", "AuditIssue", FormMethod.Post, new { @Id = "frm_Audit" }))
    {
        <!-- Master Start-->
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">Audit Issue </h3>
            </div>
            <div class="card-body">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.AuditId)

                @Html.HiddenFor(model => model.Operation)

                <div class="form-group row">
 @*                   <div class="col-sm-2">
                        <div>
                            @Html.LabelFor(model => model.AuditId)
                            @Html.DropDownListFor(model => model.AuditId, Enumerable.Empty<SelectListItem>(), new {@class = "form-control", @data_selected = Model.AuditId})
                            @Html.ValidationMessageFor(model => model.AuditId)

                        </div>
                    </div>*@

                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.IssueName)
                        @Html.TextBoxFor(model => model.IssueName, new { @class = "  form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.IssueName)
                    </div>


                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.IssueDetails)
                        @Html.TextAreaFor(model => model.IssueDetails, new { @class = "  form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.IssueDetails)
                    </div>


                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.DateOfSubmission)
                        <div class="input-group date">
                            @Html.TextBoxFor(model => model.DateOfSubmission, new { @class = "  form-control input-sm dateRange" })
                            <div class="input-group-append">
                                <div class="input-group-text"><i class="far fa-calendar-alt"></i></div>
                            </div>
                        </div>
                    </div>


                </div>


                <div class="row form-group">
                    <div class="col-sm-3">
                        @Html.LabelFor(model => model.IssuePriority)
                        @Html.DropDownListFor(model => model.IssuePriority, Enumerable.Empty<SelectListItem>(), new {@class = "form-control", @data_selected = Model.IssuePriority})
                        @Html.ValidationMessageFor(model => model.IssuePriority)
                    </div>
                </div>


                <div class="row form-group">
                    <div class="col-md-3">
                        <div class="editor-label">
                            <label>Attachments</label>
                        </div>
                        <input type="file" accept=".jpg,.jpeg, .png,.pdf, .xls, .xlsx,.docx" id="fileToUpload" name="Attachments" multiple="multiple" />

                    </div>

                </div>

                <div class="row">
                    <ul class="list-group fileGroup">

                        @foreach (AuditIssueAttachments item in Model.AttachmentsList)
                        {
                            <li class="list-group-item" id="file-@item.Id">
                                <span>
                                    @item.DisplayName
                                </span>
                                <a target="_blank" href="/AuditIssue/DownloadFile?filePath=@item.FileName" class=" ml-2 btn btn-primary btn-sm float-right ml-2">Download</a>

                                <button onclick="AuditIssueController.deleteFile('@item.Id' ,'@item.FileName')" class=" ml-2 btn btn-danger btn-sm float-right" type="button">Delete</button>


                            </li>
                        }

                    </ul>
                </div>

            </div>
        </div>

        <!-- Master End-->
    }


</div>




<div class="container-fluid">
    <div class="card">
        <div class="card-header p-2">
            @if (Model.Operation.Equals("update", StringComparison.OrdinalIgnoreCase))
            {
                <button type="button" class="btn btn-primary  pt-1 btnSave">Update</button>
            }
            else
            {
                <button type="button" class="btn btn-primary  pt-1 btnSave">
                    <i class="fa fa-save"></i>
                    Save
                </button>
            }
        </div>
    </div>
</div>


@section scripts{
    <script src="/js/app/Services/AuditIssue/AuditIssueService.js"></script>
    <script src="/js/app/Controllers/AuditIssue/AuditIssueController.js"></script>

    <script>

        $(document).ready(function () {
            AuditIssueController.init();
        });

    </script>


}

SageERP/Views/AuditIssue/Index.cshtml
@model Shampan.Models.AuditIssue


@{
    ViewData["Title"] = "Index";
}


@Html.Partial("_Header",new HeaderModel(){ HeaderName = "Audit Issues", BreadCrums = new Dictionary<string, string>()
{
    {"/AuditIssue/index/"+@Model.AuditId,"Audit Issues"},
    {"","Index"},
}})



<div class="container-fluid">
    <div class="card">
        <div class="card-header card-secondary">
            <h4 style="text-align: center"><strong>Audit Details</strong></h4>
        </div>
        <div class="card-body">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        @*                    <th scope="col"></th>
                        <th scope="col">Column 1</th>
                        <th scope="col">Column 2</th>*@
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.Code)</th>
                        <td>@Model.AuditMaster.Code</td>

                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.Name)</th>
                        <td>@Model.AuditMaster.Name</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.StartDate)</th>
                        <td>@Model.AuditMaster.StartDate</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.EndDate)</th>
                        <td>@Model.AuditMaster.EndDate</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.Location)</th>
                        <td>@Model.AuditMaster.Location</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.BusinessTarget)</th>
                        <td>@Model.AuditMaster.BusinessTarget</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.AuditStatus)</th>
                        <td>@Model.AuditMaster.AuditStatus</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.ReportStatus)</th>
                        <td>@Model.AuditMaster.ReportStatus</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.AuditTypeName)</th>
                        <td>@Model.AuditMaster.AuditTypeName</td>
                    </tr>
                    <tr>
                        <th scope="row">@Html.LabelFor(model => model.AuditMaster.TeamName)</th>
                        <td>@Model.AuditMaster.TeamName</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>



<div class="container-fluid">
    <div class="card">
        <div class="card-header p-2">
            <button type="button" title="Add New Audit"
                    data-url="/AuditIssue/Create/@Model.AuditId" onclick="GoTo(this)"
                    id="" class="NewButton">
                <i class="fa fa-plus" aria-hidden="true"></i>
                &nbsp;
                New
            </button>

        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="card card-secondary">
        <div class="card-header">
            <h3 class="card-title">
                List Of Data
            </h3>

        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped" id="AuditIssueList">
                <thead>
                    <tr>
                        <th>Action</th>
                        <th>Issue Name</th>
                        <th>Issue Priority</th>
                        <th>Date Of Submission</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>

</div>


@section scripts{

    <script src="/js/app/Services/AuditIssue/AuditIssueService.js"></script>
    <script src="/js/app/Controllers/AuditIssue/AuditIssueController.js"></script>

    <script>

        $(document).ready(function () {
            AuditIssueController.init({ auditId: @Model.AuditId});

        });

    </script>
}